import { Footer, Navbar } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import Script from 'next/script'
export const metadata: Metadata = {
  title: 'Abuzar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body className='bg-white text-black dark:bg-black dark:text-white'>
     
        <Navbar/>
        {children}
        <Footer/>
        <Script id='theme-swither' strategy='beforeInteractive'>
 {` if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
    document.documentElement.classList.add('dark')
  } else {
    document.documentElement.classList.remove('dark')
  }`}
        </Script>
        </body>
    </html>
  )
}
